# Generated by Django 3.2.13 on 2022-06-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_experience_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='jobType',
            field=models.CharField(default='', max_length=75),
        ),
    ]
