# Generated by Django 3.2.13 on 2022-06-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20220626_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
